export enum Limit {
    LEVEL_MAXSCREENSHOTS = 10,

    MAX_TAGS = 15,
    MAX_TAG_TEXTLEN = 20,
    MAX_TAG_LINKLEN = 100,
    MAX_LASTUSED_TAGS = 5,
    MAX_REVIEWCONTAINERS = 100,
    CAROUSEL_MAXMEDIA = 25,
    COMMENTARY_MAXLEN = 250,

    SAVETIMER_TIMEOUT = 10000,
    HIGH_OBJCOUNT = 40000

}